name: ze_draw
description: Comunidade digital criada para motivar e inspirar artistas de todo o mundo.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  simple_gradient_text: ^1.2.4
  supabase_flutter: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
