name: ze_draw
description: Comunidade digital criada para motivar e inspirar artistas de todo o mundo.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  simple_gradient_text: ^1.2.4
  supabase_flutter: ^1.8.1
  dotted_border: ^2.0.0+3
  uuid: ^3.0.6
  file_picker: ^5.3.0
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  gradient_borders: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  popover: ^0.2.8+2
  cached_network_image: ^3.2.3
  persistent_bottom_nav_bar: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
