name: Testes
on:
  push:
    branches:
      - master
      - development
      - 'feature/**'

jobs:
  testar:
    runs-on: ubuntu-latest
    name: Executar testes com flutter
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter test